-- 建立資料庫
CREATE DATABASE Account;
USE Account;

-- 建立資料表 USER_
CREATE TABLE User_(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserName VARCHAR(50) NOT NULL UNIQUE,
    UserPassword VARCHAR(255) NOT NULL, -- 支援加密密碼
    Phone VARCHAR(15),
    Email VARCHAR(255) UNIQUE
);

-- 建立資料表 POST
CREATE TABLE Post (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AuthorID INT NOT NULL,
    Title TEXT,
    Content TEXT NOT NULL,
    Photo TEXT,
    PostDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AuthorID) REFERENCES User_(ID) ON DELETE CASCADE
);

-- 建立資料表 COMMENTS
CREATE TABLE Comments (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PostID INT NOT NULL,
    UserID INT NOT NULL,
    Content TEXT NOT NULL,
    CommentDate DATE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User_(ID) ON DELETE CASCADE,
    FOREIGN KEY (PostID) REFERENCES Post(ID) ON DELETE CASCADE
);

-- 建立資料表 TAGS
CREATE TABLE Tags (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TagName VARCHAR(50) NOT NULL UNIQUE,
    TagDescription TEXT
);

-- 建立關聯表 POST_TAGS
CREATE TABLE PostTags (
    PostID INT NOT NULL,
    TagID INT NOT NULL,
    PRIMARY KEY (PostID, TagID),
    FOREIGN KEY (PostID) REFERENCES Post(ID) ON DELETE CASCADE,
    FOREIGN KEY (TagID) REFERENCES Tags(ID) ON DELETE CASCADE
);


-- 顯示資料表
SHOW TABLES;
DESC User_;
DESC Post;
DESC Comments;
DESC Tags;
DESC PostTags;
